### ISSUE TITLE
Scrolling when not touchhold for some time

### ISSUE THREAD

**Issue by errnoenomem** [drag-drop-touch-js/dragdroptouch#26]
Is there anyway to allow scrolling when you haven't press and hold a draggable element for say 1000 ms? right now if I try to swipe on an element that is draggable, it just won't do anything.

**Comment by ricefieldboy** [comment]
I was actually able to get it working perfectly just changing 2 lines of code.

`if ('ontouchstart' in document) {
                var d = document, ts = this._touchstart.bind(this), tm = this._touchmove.bind(this), te = this._touchend.bind(this), opt = supportsPassive ? { passive: false, capture: false } : false;
                d.addEventListener('touchstart', ts); 
                d.addEventListener('touchmove', tm, opt);
                d.addEventListener('touchend', te);
                d.addEventListener('touchcancel', te);
            }`

**Comment by Bernardo-Castilho** [comment]
Nice! Thanks for sharing this solution!

**Comment by koz1ma** [comment]
The scrolling was still happening when i had used this polyfill so i fixed by adding passive:false to the touchmove event like:
d.addEventListener('touchmove', tm, {passive: false});

**Comment by pumpknhd** [comment]
Works! Requires:
- d.addEventListener('touchstart', ts, opt) -> d.addEventListener('touchstart', ts)
- d.addEventListener('touchmove', tm, opt) -> d.addEventListener('touchmove', tm, {passive: false})
- commented out a preventDefault() (line 188)
- turn pressholdmode = true

I also had to add the following CSS when on iOS so that texts are not selected when dragging.
```
  .disableSelect {     
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;  
  }
```

Here's what I used to detect if it's iOS:
`(/iPad|iPhone|iPod/.test(navigator.platform) || (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1))`

**Comment by welkinwong** [comment]
> 我实际上可以通过更改2行代码来使其工作。
> 
> 我刚刚从d.addEventListener（'touchstart'，ts，opt）;中删除了opt参数；并注释掉了preventDefault（）（第188行）。将pressholdmode = true设置为有效

it works!👍

**Comment by Pomax** [comment]
I'm closing this mostly because of how much time has passed. If this is still a concern, please file a new issue. I recently signed on to this project and would like to make sure we're covering all the bases, while also making sure there are no lingering issues based on old code.
