### ISSUE TITLE
drag image for elements with 'transform' styles are incorrectly positioned

### ISSUE THREAD

**Issue by Ragzouken** [drag-drop-touch-js/dragdroptouch#28]
In my case, I'm using a translate transform style and the drag image is way offscreen. My workaround is to add `this._img.style.transform = 'none';` in the same place where `left` and `top` are set to -9999. I'm not sure if this has other unwanted side effects though, but it works in my use case,

**Comment by Pomax** [comment]
I'm closing this mostly because of how much time has passed and how much the code has changed since this issue was filed. If this is still a concern, please file a new issue. I recently signed on to this project and would like to make sure we're covering all the bases, while also making sure there are no lingering issues based on old code.
