### ISSUE TITLE
Injector error

### ISSUE THREAD

**Issue by jeppebundsgaard** [drag-drop-touch-js/dragdroptouch#39]
When running the demo, I get the following error in the console. 

> Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.5/$injector/modulerr?p0=app&…ax%2Flibs%2Fangularjs%2F1.4.5%2Fangular.min.js%3A292%3A64%0A

I get a similar error when integrating DragDropTouch in my own project. Any ideas?

**Comment by Pomax** [comment]
I'm closing this mostly because of how much time has passed and how much the code has changed since this issue was filed. If this is still a concern, please file a new issue. I recently signed on to this project and would like to make sure we're covering all the bases, while also making sure there are no lingering issues based on old code.
