### ISSUE TITLE
How to use Drag Drop Touch in Angular 10

### ISSUE THREAD

**Issue by WisarutBholsithi** [drag-drop-touch-js/dragdroptouch#43]
Dear Sir,
After taking a look at DragDropTouch polyfill demo, it seems to me it has been designed for AngularJS with Wijmo Licensing .... I just wonder how to use your library DragDropTouch polyfill for my web app that use Angular 10 though.

Furthermore, I have found that without Wijmo Licensing, I cannot simulate the drag drop using responsive simulation of mobile devices (I-pad, I-phone, Galaxy note, Galaxy mobile or so).

**Comment by Bernardo-Castilho** [comment]
Hi.

The DragDropTouch library is based on plain HTML5. It does not require, use, or depend on any frameworks or libraries.

It does of course work with AngularJS, Angular/latest, React, Vue, etc.

As for Wijmo, it uses HTML5 drag/drop. Because of this, DragDropTouch can be used to add drag/drop support on mobile devices.

I hope that clarifies things.

**Comment by WisarutBholsithi** [comment]
Thanks a lot for your quick response for my inquiry.
I'm going to try using your DragDropTouch to deal with the issue image drag drop from mobile devices (I-Pad, I-Phone, Galaxy Note, Galaxy S9 or so) using various browsers (Google Chrome, Mozilla Firefox, or so).

Wisarut.

________________________________

**Comment by Pomax** [comment]
I'm closing this mostly because of how much time has passed and how much the code has changed since this issue was filed. If this is still a concern, please file a new issue. I recently signed on to this project and would like to make sure we're covering all the bases, while also making sure there are no lingering issues based on old code.
