### ISSUE TITLE
Add support for Shadow DOM

### ISSUE THREAD

**Issue by AndrewPerson** [drag-drop-touch-js/dragdroptouch#44]
Dear Sir,
I'm wondering if you could add support for Shadow DOM to this polyfill. I've been testing it with Lit and have found that any elements in a Shadow DOM on a mobile screen do not have any of the drags events fired, and are just not draggable in general. Here's a [demonstration](https://html-sandbox.profsmart.repl.co). (It doesn't use Lit, but it uses Shadow DOM.)

Sincerely,
Andrew

**Comment by Pomax** [comment]
I'm closing this mostly because of how much time has passed and how much the code has changed since this issue was filed. If this is still a concern, please file a new issue. I recently signed on to this project and would like to make sure we're covering all the bases, while also making sure there are no lingering issues based on old code.
