### ISSUE TITLE
NPM package outdated

### ISSUE THREAD

**Issue by raphaelsantos** [drag-drop-touch-js/dragdroptouch#52]
First, thanks for this polyfill, it's been a lifesaver :)

We have been using the NPM package on my project to get drag interactions working on Safari, and recently we ran into problems with touch events on Chrome (ChromeOS/Windows). 

I spent a bit of time debugging and when I was about to propose a PR with a fix, I found out that it has already be fixed in this commit:  https://github.com/Bernardo-Castilho/dragdroptouch/commit/63e4a9a7e5b833240808402512fc008d772bac44, but the update never made it to NPM. The latest version (1.3.1) precedes this update.

If you could publish the latest updates to NPM, this would benefit a lot of users who have relying on the NPM package. Thanks again for the great work.

**Comment by Bernardo-Castilho** [comment]
Hi Raphael

I am very glad to know the polyfill has been useful to you, thanks for the feedback!

Unfortunately, I am not involved in the NPM version of the package.

I was busy at the time and someone else took over this task and published it to NPM themselves. I don’t even remember the name of the guy who actually published this, the contributor name is just “mesmotronic”, so I don’t even know how to get in touch with him/her. But it looks like they haven’t updated the package in a while (2 years)...

I will try to find the contact of the publisher, but I don’t know if I will be able to.

Maybe you’d like to create your own version on NPM?




Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Raphael Dos ***@***.***>
Enviado:domingo, 4 de setembro de 2022 12:12
Para: ***@***.***>
***@***.***>
Assunto: [Bernardo-Castilho/dragdroptouch] NPM package outdated (Issue #52)


First, thanks for this polyfill, it's been a lifesaver :)

We have been using the NPM package on my project to get drag interactions working on Safari, and recently we ran into problems with touch events on Chrome (ChromeOS/Window).

I spent a bit of time debugging and when I was about to propose a PR with a fix, I found out that it has already be fixed in this commit: 63e4a9a<https://github.com/Bernardo-Castilho/dragdroptouch/commit/63e4a9a7e5b833240808402512fc008d772bac44>, but the fix never made it to NPM. The latest version (1.3.1) precedes this fix.

If you could publish the latest updates to NPM, this would benefit a lot of users who have relying on the NPM package. Thanks again for the great work.

**Comment by calm-prog** [comment]
Hi there,

First of all, great library indeed, thanks for the good work on it! 

However, now it's been 4 years since the last release, and I assume most folks consume this library through npm, so people don't really have access to a lot of the nice fixes that I can see merged. 

Isn't there still anyone among the contributors who is involved with the versioning? I can see "mesmotronic" is not in the list, so I guess he left the project. It would also probably most wise not to release it separately, unless it's the only option.

**Comment by Bernardo-Castilho** [comment]
Hello Ferenc

Glad to know you like the library.

I wrote the original version and put it on gituhb (https://github.com/Bernardo-Castilho/dragdroptouch).

Unfortunately, I did not write the NPM version. I do know a couple of people took the initiative and created NPM packages for it. But I am not a contributor to those packages and I don't follow them actively...

Here's a list of the NPM packages I found today:

      https://www.npmjs.com/package/drag-drop-touch (3.9k downloads/wk)
      https://www.npmjs.com/package/dragdroptouch-bug-fixed (470)
      https://www.npmjs.com/package/drag-drop-touch-polyfill (593)

It appears the top one is the most active.

I guess that's the one you mentioned, last updated 4 years ago by mesmotronic...

Perhaps it's time for you to take over 😉...






[https://static-production.npmjs.com/338e4905a2684ca96e08c7780fc68412.png]<https://www.npmjs.com/package/drag-drop-touch-polyfill>
drag-drop-touch-polyfill<https://www.npmjs.com/package/drag-drop-touch-polyfill>
fork from https://github.com/Bernardo-Castilho/dragdroptouch and made little changes.. Latest version: 1.0.0, last published: 7 years ago. Start using drag-drop-touch-polyfill in your project by running `npm i drag-drop-touch-polyfill`. There is 1 other project in the npm registry using drag-drop-touch-polyfill.
www.npmjs.com

[https://static-production.npmjs.com/338e4905a2684ca96e08c7780fc68412.png]<https://www.npmjs.com/package/dragdroptouch-bug-fixed>
dragdroptouch-bug-fixed<https://www.npmjs.com/package/dragdroptouch-bug-fixed>
Polyfill that enables HTML5 drag drop support on mobile (touch) devices. Latest version: 1.0.8, last published: 3 years ago. Start using dragdroptouch-bug-fixed in your project by running `npm i dragdroptouch-bug-fixed`. There is 1 other project in the npm registry using dragdroptouch-bug-fixed.
www.npmjs.com

[https://static-production.npmjs.com/338e4905a2684ca96e08c7780fc68412.png]<https://www.npmjs.com/package/drag-drop-touch>
drag-drop-touch<https://www.npmjs.com/package/drag-drop-touch>
Polyfill that enables HTML5 drag drop support on mobile (touch) devices. Latest version: 1.3.1, last published: 4 years ago. Start using drag-drop-touch in your project by running `npm i drag-drop-touch`. There are 5 other projects in the npm registry using drag-drop-touch.
www.npmjs.com

________________________________

**Comment by Pomax** [comment]
I'm closing this as it's been several years and things have changed. The npm package _is_ still out of date, but that's because someone unrelated to the project "hijacked" the publication. See #70 for more information.

**Comment by floteslof** [comment]
For anyone interested, there is an easy workaround for this package not being available for NPM. You can install the Github package directly using `npm install git+https://github.com/drag-drop-touch-js/dragdroptouch.git`. This makes it available by importing it via ES6 for example.
```
import { enableDragDropTouch } from 'drag-drop-touch';
```

**Comment by Pomax** [comment]
But do note that there's really no need to `npm install` anything: it's a client-side library, don't bundle it in, just link to it and take advantage of the browser being able to cache that CDN url:

`import { enableDragDropTouch } from "https://cdn.jsdelivr.net/gh/drag-drop-touch-js/dragdroptouch@master/dist/drag-drop-touch.esm.min.js";`
