### ISSUE TITLE
Breaks Bootstrap 3 dropdown menu

### ISSUE THREAD

**Issue by freescout-helpdesk** [drag-drop-touch-js/dragdroptouch#62]
Somehow this Polyfill breaks Bootstrap 3 dropdown submenu functionality on mobile devices: https://github.com/freescout-helpdesk/freescout/issues/3708

**Comment by freescout-helpdesk** [comment]
Maybe we can come up with some quick hack not to apply this Polyfill to the Bootstrap menu.

**Comment by Pomax** [comment]
I'm closing this mostly because of how much time has passed and how much the code has changed since this issue was filed. If this is still a concern, please file a new issue. I recently signed on to this project and would like to make sure we're covering all the bases, while also making sure there are no lingering issues based on old code.
