### ISSUE TITLE
Set up github pages for the master branch

### ISSUE THREAD

**Issue by Pomax** [drag-drop-touch-js/dragdroptouch#71]
It looks like the demo link is not currently being served from the master branch - I do not have settings access, @Bernardo-Castilho could you double check that the "pages" section in settings points to the master branch's root directory?

**Comment by Pomax** [comment]
@Bernardo-Castilho quick ping - I'm more than happy to set that up, but don't have settings access for this repo of course (so as much as I trust myself to not destroy someone else's repo, I don't expect anyone else to just trust me with their keys =D)

**Comment by Pomax** [comment]
It looks like http://bernardo-castilho.github.io/DragDropTouch/demo/index.htm still works, pointing to the original content, so it looks like page building might be turned off atm?

**Comment by Bernardo-Castilho** [comment]
The original demo still works because it has a static copy of the library (DragDropTouch.js). It is *not* updated automatically when the library changes.

I suggest you make a new sample (I'm sure you have one already) and link to that from the readme.

**Comment by Pomax** [comment]
I have, but the problem is that your .io page does not appear to be using the github "pages" setup, so updating the master branch does not update the .io hosted content (they changed how gh-pages works a few times over the last 8 years) so the new page I made (`index.html` rather than `index.htm`) doesn't exist on the github.io side (it's still serving the original content).

So if would be useful if the "pages" settings were set up to use the `master` branch, and the `root` directory for that, so that github automatically keeps the web page in sync with the repo.

**Comment by Bernardo-Castilho** [comment]
Hello Mr Pomax

I made the change you suggested.

I hope you can deploy your sample as part of the readme now.

Given the amount of work and commitment to this project, I am tempted to transfer the ownership of the repo to you. Would that be OK?



Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

________________________________
De: Pomax ***@***.***>
Enviado: Thursday, July 25, 2024 1:44:07 PM
Para: Bernardo-Castilho/dragdroptouch ***@***.***>
Cc: Bernardo Castilho ***@***.***>; Mention ***@***.***>
Assunto: Re: [Bernardo-Castilho/dragdroptouch] Set up github pages for the master branch (Issue #71)


I have, but the problem is that your .io page does not appear to be using the github "pages" setup, so updating the master branch does not update the .io hosted content (they changed how gh-pages works a few times over the last 8 years) so the new page I made (index.html rather than index.htm) doesn't exist on the github.io side (it's still serving the original content).

So if would be useful if the "pages" settings were set up to use the master branch, and the root directory for that, so that github automatically keeps the web page in sync with the repo.

**Comment by Pomax** [comment]
If you feel that's easier then that's an option, but then it might make more sense to create a "drag-drop-touch.js" free organization through https://github.com/settings/organizations and transfer ownership to that organization instead (that way there can be multiple admins, and the new github repository URL would be more "trustworthy")

**Comment by Bernardo-Castilho** [comment]
Great suggestion. Done!


Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

________________________________
De: Pomax ***@***.***>
Enviado: Friday, July 26, 2024 12:19:34 PM
Para: Bernardo-Castilho/dragdroptouch ***@***.***>
Cc: Bernardo Castilho ***@***.***>; Mention ***@***.***>
Assunto: Re: [Bernardo-Castilho/dragdroptouch] Set up github pages for the master branch (Issue #71)


If you feel that's easier then that's an option, but then it might make more sense to create a "drag-drop-touch.js" free organization through https://github.com/settings/organizations and transfer ownership to that organization instead (that way there can be multiple admins, and the new github repository URL would be more "trustworthy")

**Comment by Pomax** [comment]
Nice! I'll dive in the pages section =)

**Comment by Pomax** [comment]
pages action set up, https://drag-drop-touch-js.github.io/dragdroptouch/demo looks to be working, so I've updated the README.md with the new link, too. I'll file a new issue for refining the page itself.

**Comment by Bernardo-Castilho** [comment]
👍👍
